DROP TABLE IF EXISTS public.everytype;
DROP TYPE IF EXISTS choices;

CREATE TYPE choices AS ENUM ('yes', 'no', 'maybe');
CREATE TABLE public.everytype (
	c_vchar_alt_def varchar NULL,
	c_vchar_alt_255 varchar(255) NOT NULL,
	c_bigint int8 NULL,
	c_bigserial bigserial,
	c_bool boolean NULL,
	c_bytea bytea NULL,
	c_char_def character NULL,
	c_char_144 character(144) NULL,
	c_vchar_def character varying NULL,
	c_vchar_144 character varying(144) NULL,
	c_cidr cidr NULL,
	c_date date NULL,
	c_double double precision NULL,
	c_double_alias float8 NULL,
	c_inet inet NULL,
	c_integer integer NULL,
	c_int int NULL,
	c_int4 int4 NULL,
	c_json json NULL,
	c_jsonb jsonb NULL,
	c_macaddr macaddr NULL,
	c_numeric numeric(8, 2) NULL,
	c_real real NULL,
	c_float4 float4 NULL,
	c_smallint smallint NULL,
	c_int2 int2 NULL,
	c_smallserial smallserial,
	c_serial serial,
	c_text text NULL,
	c_time  time  NULL,
	c_time_wtz  time without time zone NULL,
	c_timetz time with time zone NULL,
	c_timetz_alias timetz NULL,
	c_timestamp timestamp NULL,
	c_timestamp_wtz timestamp without time zone NULL,
	c_uuid uuid NULL,
  c_enum choices NULL
);
