version: '3.6'

services:
  ag-postgres:
    image: postgres:14-alpine
    hostname: ag-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: artgen
      POSTGRES_USER: artgen
      POSTGRES_PASSWORD: artgen
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    volumes:
      - ag_postgresql:/var/lib/postgresql/data/pgdata

  ag-search:
    image: getmeili/meilisearch:latest
    hostname: ag-search
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ag_search:/data.ms

volumes:
  ag_postgresql:
  ag_search:
