version: '3.6'

services:
  # Postgres server
  tdb-postgres:
    image: postgres:14-alpine
    hostname: tdb-postgres
    environment:
      POSTGRES_DB: artgen
      POSTGRES_USER: artgen
      POSTGRES_PASSWORD: artgen
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    logging:
      driver: "none"

  # MariaDB server
  tdb-mariadb:
    image: mariadb:latest
    hostname: tdb-mariadb
    environment:
      MARIADB_DATABASE: artgen
      MARIADB_USER: artgen
      MARIADB_PASSWORD: artgen
      MARIADB_ROOT_PASSWORD: artgen
      TZ: UTC
    logging:
      driver: "none"
    cap_add:
      - "SYS_NICE"

  # MySQL server
  tdb-mysql:
    image: mysql:latest
    hostname: tdb-mysql
    environment:
      MYSQL_DATABASE: artgen
      MYSQL_USER: artgen
      MYSQL_PASSWORD: artgen
      MYSQL_ROOT_PASSWORD: artgen
      TZ: UTC
    logging:
      driver: "none"
    cap_add:
      - "SYS_NICE"

  # Test for Postgres
  tinst-postgres:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "postgres://artgen:artgen@tdb-postgres:5432/artgen"
    command: yarn test
    depends_on:
      - tdb-postgres
    restart: "no"

  # Test for MariaDB
  tinst-mariadb:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "mariadb://artgen:artgen@tdb-mariadb:3306/artgen"
    command: yarn test
    depends_on:
      - tdb-mariadb
    restart: "no"

  # Test for MySQL
  tinst-mysql:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "mysql://artgen:artgen@tdb-mysql:3306/artgen"
    command: yarn test
    depends_on:
      - tdb-mysql
    restart: "no"

  # Test for SQLite memory
  tinst-sqlite-memory:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "sqlite::memory:"
    command: yarn test
    restart: "no"

  # Test for SQLite file
  tinst-sqlite-file:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "sqlite:./test.db"
    command: yarn test
    restart: "no"
