version: '3.6'

services:
  # Postgres server
  tdb-postgres:
    image: postgres:14-alpine
    hostname: tdb-postgres
    environment:
      POSTGRES_DB: artgen
      POSTGRES_USER: artgen
      POSTGRES_PASSWORD: artgen
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    logging:
      driver: "none"

  # Test for Postgres
  tinst-postgres:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "postgres://artgen:artgen@tdb-postgres:5432/artgen"
    command: yarn test
    depends_on:
      - tdb-postgres
    restart: "no"

  # Test for SQLite memory
  tinst-sqlite-memory:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "sqlite::memory:"
    command: yarn test
    restart: "no"

  # Test for SQLite file
  tinst-sqlite-file:
    image: node:16
    working_dir: /srv
    volumes:
      - ./:/srv
    environment:
      ARTGEN_DATABASE_DSN: "sqlite:./test.db"
    command: yarn test
    restart: "no"
