version: '3.6'

services:
  ag-postgres:
    image: postgres:14-alpine
    hostname: ag-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: artgen
      POSTGRES_USER: artgen
      POSTGRES_PASSWORD: artgen
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    volumes:
      - ag_postgresql:/var/lib/postgresql/data/pgdata

  ag-mariadb:
    image: mariadb:latest
    hostname: ag-mariadb
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: artgen
      MARIADB_USER: artgen
      MARIADB_PASSWORD: artgen
      MARIADB_ROOT_PASSWORD: artgen
      TZ: UTC
    volumes:
      - ag_mariadb:/var/lib/mysql

  ag-mysql:
    image: mysql:latest
    hostname: ag-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: artgen
      MYSQL_USER: artgen
      MYSQL_PASSWORD: artgen
      MYSQL_ROOT_PASSWORD: artgen
      TZ: UTC
    volumes:
      - ag_mysqldb:/var/lib/mysql

volumes:
  ag_postgresql:
  ag_mysqldb:
  ag_mariadb:
