export enum FieldType {
  BOOLEAN = 'boolean',
  DATETIME = 'timestamp',
  DATEONLY = 'dateonly',
  TIME = 'time',
  INTEGER = 'int',
  JSON = 'json',
  TEXT = 'text',
  UUID = 'uuid',
  STRING = 'string',
  CHAR = 'char',
  BIGINT = 'bigint',
  TINYINT = 'tinyint',
  SMALLINT = 'smallint',
  MEDIUMINT = 'mediumint',
  FLOAT = 'float',
  REAL = 'real',
  DOUBLE = 'double',
  DECIMAL = 'decimal',
  BLOB = 'blob',
  ENUM = 'enum',

  HSTORE = 'hstore',
  JSONB = 'jsonb',
  CIDR = 'cidr',
  INET = 'inet',
  MACADDR = 'macaddr',
}
